import { Food } from './shared/models/Food';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Vegetable Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Margherita Pizza',
    price: 8,
    cookTime: '30-40',
    favorite: true,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'assets/food-2.jpg',
    tags: ['FastFood', 'Pizza', 'Dinner'],
  },
  {
    id: '3',
    name: 'Pepperoni Pizza',
    price: 10,
    cookTime: '35-45',
    favorite: true,
    origins: ['United States'],
    stars: 4.2,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Pizza', 'Dinner'],
  },
  {
    id: '4',
    name: 'Hawaiian Pizza',
    price: 11,
    cookTime: '45-55',
    favorite: false,
    origins: ['Canada'],
    stars: 4.1,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Pizza', 'Dinner'],
  },
  {
    id: '5',
    name: 'BBQ Chicken Pizza',
    price: 12,
    cookTime: '50-60',
    favorite: true,
    origins: ['United States'],
    stars: 4.7,
    imageUrl: 'assets/food-5.jpg',
    tags: ['FastFood', 'Pizza', 'Dinner'],
  },
  {
    id: '6',
    name: 'Mushroom Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: 'Meat Lovers Pizza',
    price: 13,
    cookTime: '50-60',
    favorite: true,
    origins: ['United States'],
    stars: 4.9,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Pizza', 'Dinner'],
  },
  {
    id: '8',
    name: 'Greek Pizza',
    price: 10,
    cookTime: '45-55',
    favorite: false,
    origins: ['Greece'],
    stars: 4.3,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Dinner'],
  },
  {
    id: '9',
    name: 'Four Cheese Pizza',
    price: 11,
    cookTime: '40-50',
    favorite: true,
    origins: ['Italy'],
    stars: 4.6,
    imageUrl: 'assets/food-9.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '10',
    name: 'Veggie Delight Pizza',
    price: 10,
    cookTime: '45-55',
    favorite: false,
    origins: ['United States'],
    stars: 4.2,
    imageUrl: 'assets/food-10.jpg',
    tags: ['FastFood', 'Pizza', 'Dinner'],
  },
];
