// import { Food } from './shared/models/Food';
// import { Tag } from './shared/models/Tag';

export const sample_foods: any[] = [
  {
    id: "1",
    name: "Vegetable Pizza",
    price: 9,
    cookTime: "40-50",
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "assets/food-1.jpg",
    tags: ["FastFood"],
  },
  {
    id: "2",
    name: "Margherita Pizza",
    price: 8,
    cookTime: "30-40",
    favorite: true,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: "assets/food-2.jpg",
    tags: ["FastFood"],
  },
  {
    id: "3",
    name: "Pepperoni Pizza",
    price: 10,
    cookTime: "35-45",
    favorite: true,
    origins: ["United States"],
    stars: 4.2,
    imageUrl: "assets/food-3.jpg",
    tags: ["FastFood"],
  },
  {
    id: "4",
    name: "Hawaiian Pizza",
    price: 11,
    cookTime: "45-55",
    favorite: false,
    origins: ["Canada"],
    stars: 4.1,
    imageUrl: "assets/food-4.jpg",
    tags: ["Pizza"],
  },
  {
    id: "5",
    name: "BBQ Chicken Pizza",
    price: 12,
    cookTime: "50-60",
    favorite: true,
    origins: ["United States"],
    stars: 4.7,
    imageUrl: "assets/food-5.jpg",
    tags: ["Pizza"],
  },
  {
    id: "6",
    name: "Mushroom Pizza",
    price: 9,
    cookTime: "40-50",
    favorite: false,
    origins: ["Italy"],
    stars: 4.0,
    imageUrl: "assets/food-6.jpg",
    tags: ["Lunch"],
  },
  {
    id: "7",
    name: "Meat Lovers Pizza",
    price: 13,
    cookTime: "50-60",
    favorite: true,
    origins: ["United States"],
    stars: 4.9,
    imageUrl: "assets/food-7.jpg",
    tags: ["Lunch"],
  },
  {
    id: "8",
    name: "Greek Pizza",
    price: 10,
    cookTime: "45-55",
    favorite: false,
    origins: ["Greece"],
    stars: 4.3,
    imageUrl: "assets/food-8.jpg",
    tags: ["SlowFood"],
  },
  {
    id: "9",
    name: "Four Cheese Pizza",
    price: 11,
    cookTime: "40-50",
    favorite: true,
    origins: ["Italy"],
    stars: 4.6,
    imageUrl: "assets/food-9.jpg",
    tags: ["SlowFood"],
  },
  {
    id: "10",
    name: "Veggie Delight Pizza",
    price: 10,
    cookTime: "45-55",
    favorite: false,
    origins: ["United States"],
    stars: 4.2,
    imageUrl: "assets/food-10.jpg",
    tags: ["Hamburger"],
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shangai",
    isAdmin: false,
  },
];
